### ISSUE TITLE
yarn tsc fails 

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#1]
packages/app/src/App.tsx:217:10 - error TS2604: JSX element type 'Mermaid' does not have any construct or call signatures.

217         <Mermaid />

**Comment by johanneswuerbach** [comment]
Could you elaborate a bit more what you are trying to achieve? This package has no `packages/app/src/App.tsx` path.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Sorry, my App.tsx basically contains

import { Mermaid } from 'backstage-plugin-techdocs-addon-mermaid';

<Route
      path="/docs/:namespace/:kind/:name/*"
      element={<TechDocsReaderPage />}
    >
      {techDocsPage}
      <TechDocsAddons>
        <Mermaid />
      </TechDocsAddons>
    </Route>

**Comment by johanneswuerbach** [comment]
Did you add `"backstage-plugin-techdocs-addon-mermaid": "^0.2.0",` to your `package.json` and ran `yarn install`?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Yes, I did that.
It is actually complaining about the typescript error not the install error

**Comment by johanneswuerbach** [comment]
Found it 🎉 , should be fixed in `backstage-plugin-techdocs-addon-mermaid@0.2.1`

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Excellent. This resolved. I will close the ticket now
