### ISSUE TITLE
Warning in CI pipeline

### ISSUE THREAD

**Issue by axdotl** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#12]
After adding the Addon to a Backstage App the build contain warnings. As warning are treated as error by default on CI, the build breaks.

```plain
webpack compiled with 2 warnings
WARNING in ../../node_modules/mermaid/dist/mermaid.core.mjs 27645:52-67
Critical dependency: the request of a dependency is an expression

WARNING in ../../node_modules/mermaid/dist/mermaid.core.mjs 27659:52-63
Critical dependency: the request of a dependency is an expression
```

Did you manage to solve these warning?
Because using `CI=false yarn build` in the pipeline feels a bit odd.

**Comment by axdotl** [comment]
When raising this issue I was on `1.7.0`, but also after upgrade to `1.8.2` the issue still exists.

Are there any further information I could provide?

**Comment by johanneswuerbach** [comment]
Maybe the node and yarn version? As said I don’t see this when doing a `yarn build` 🤔ls there anything specific required to enable yarn treating warnings as errors?

**Comment by axdotl** [comment]
I'm using following version:
- node: v16.18.1
- yarn: v1.22.17

To reproduce the behavior on CI system, you can try following command:

```
CI=true yarn build
```

**Comment by johanneswuerbach** [comment]
In a newly generated backstage app, I don't see a `build` command 🤔 

```
% CI=true yarn build
yarn run v1.22.15
error Command "build" not found.
```

My `package.json` scripts` sections looks like:

```
"scripts": {
    "dev": "concurrently \"yarn start\" \"yarn start-backend\"",
    "start": "yarn workspace app start",
    "start-backend": "yarn workspace backend start",
    "build:backend": "yarn workspace backend build",
    "build:all": "backstage-cli repo build --all",
    "build-image": "yarn workspace backend build-image",
    "tsc": "tsc",
    "tsc:full": "tsc --skipLibCheck false --incremental false",
    "clean": "backstage-cli repo clean",
    "test": "backstage-cli repo test",
    "test:all": "backstage-cli repo test --coverage",
    "lint": "backstage-cli repo lint --since origin/master",
    "lint:all": "backstage-cli repo lint",
    "prettier:check": "prettier --check .",
    "create-plugin": "backstage-cli create-plugin --scope internal",
    "new": "backstage-cli new --scope internal"
  },
```

**Comment by axdotl** [comment]
Yes, the scripts changed in the past. Actually `build` was renamed to `build:all` but executes the same. So you could try

```
CI=true yarn build:all
```

**Comment by johanneswuerbach** [comment]
Looks like this was a bug in an old mermaid version and is already resolved 🎉  https://github.com/mermaid-js/mermaid/issues/3781

I'll bump the required version here, but you should be already able to update it yourself :-)

**Comment by johanneswuerbach** [comment]
I'll have a look, but there are some issues with `react-router-dom`. Could you open a new issue for that?

**Comment by axdotl** [comment]
Thanks a lot! Will do.

**Comment by axdotl** [comment]
Sorry if I'm nitpicking, but would you mind to add a git tag for release `0.3.2`?

**Comment by johanneswuerbach** [comment]
Totally, actually just missed the push.
