### ISSUE TITLE
C4Context not recognized

### ISSUE THREAD

**Issue by jedelson-pagerduty** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#22]
A diagram like those described on https://mermaid.js.org/syntax/c4c.html is not rendered. It seems like `C4Context` is not a recognized start token in https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid/blob/main/src/Mermaid/hooks.ts#L17

Before submitting a pull request for this, was this intentional because the syntax is experimental?

**Comment by johanneswuerbach** [comment]
Just missing, not intentional 👍 

Happy to review a PR.
