### ISSUE TITLE
Breaks with mkdocs-techdocs-core 1.2.0

### ISSUE THREAD

**Issue by bforbis** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#29]
The latest [mkdocs-techdocs-core version 1.2.0](https://github.com/backstage/mkdocs-techdocs-core#120) does not render mermaid anymore with this addon. The last known working compatible version with this add-on is 1.1.7

**Comment by markandersontrocme** [comment]
@bforbis any idea what is causing this? If you have logs I can try to give it a look

**Comment by jtreher** [comment]
hah, my goodness. I was just submitting an issue for this with the exact same fix. Should have checked the issues!
