### ISSUE TITLE
Update to newest Mermaid version?

### ISSUE THREAD

**Issue by MeikPiepmeyer** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#44]
This plugin currently uses Mermaid 10.3.0, the latest release is 10.8.0. Is if possible to update to this version to enable usage of the recently added diagrams like the block diagram? http://mermaid.js.org/syntax/block.html

**Comment by johanneswuerbach** [comment]
The plugin only has a minimum dependency of `10.3.0`, but also works with `10.8.0` or newer, you can use `yarn upgrade` or similar to upgrade sub-dependencies to newer allowed versions.

**Comment by MeikPiepmeyer** [comment]
Thanks a lot - I'll report this back to my collegues who actually operate our backstage instance.

**Comment by jtreher** [comment]
@johanneswuerbach  Do you want to keep this at 10.3.0. I bumped it in #53 , but I can revert that part.
