### ISSUE TITLE
Is there a way to use elk renderer for the specific diagram?

### ISSUE THREAD

**Issue by PavelPolyakov** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#47]
Good day,

Thanks for creating and supporting this plugin.

I saw that Mermaid supports renderer switch: https://mermaid.js.org/syntax/flowchart.html?#renderer

Here is an example: https://mermaid.live/edit#pako:eNpVkE1ugzAQha9iedVKcAEWlRpos0nUqs2qmMUID9gK9ljGKIqAu9cuTX9mNZr3vZlnz7wlibzg3UCXVoEP7FQJy2I91qXyegwGxobl-cOyx8AMWbwubHe3JzYqck7b_n7jdwli5XxIGLKgtD2vm1R--V8sLqyqD-ACueavcrrQwp5q_ari-v-K8hhdz3UHRQd5C56V4BuecYPegJYx-pwMggeFBgUvYiuxg2kIgmfbLvH7vATMt-k394ZWoke_mXE4C56IGH6Nh2AK9H61LY8BhhEzPjkJASsNvQfzM0WpA_nj9pst2U730ezAfhDdqPUT0Nt2zA

Is there a way to mention the `defaultRenderer` in the diagram definition? Maybe we shall consider making it possible to configure this per diagram.

**Comment by johanneswuerbach** [comment]
Hey @PavelPolyakov ,

you should be able to write `%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%` inside your diagram when you run `backstage-plugin-techdocs-addon-mermaid@0.12.1`.
