### ISSUE TITLE
mermaid does not render on navigation, only with the page reload

### ISSUE THREAD

**Issue by PavelPolyakov** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#5]
hi @johanneswuerbach , 

First of all thanks for the plugin it's great to have Mermaid in the docs.

I've spot an issue, that diagrams are only rendered with the complete page reload. In case you have "complex" or nested documentation, then there is no render, unless you refresh the page.

here is the demo:
https://user-images.githubusercontent.com/839290/171832064-7598a602-d4b6-4d74-b5fc-62f754a43400.mp4

I wonder if something might be done with it? Or it's a limitation of the tech docs.

Regards,

**Comment by PavelPolyakov** [comment]
hi @johanneswuerbach, sorry for a ping, just want to ask for the assessment. Do you consider this as a bug? Do you have thoughts if this might be fixed or `backstage` addons integration is missing functionality to handle such behaviour currently.

Regards,

**Comment by PavelPolyakov** [comment]
@johanneswuerbach hm, thanks, it must be my side then. I will double check and report. I use Chrome.

**Comment by PavelPolyakov** [comment]
Hi @johanneswuerbach,

I've tested it locally and it has worked indeed. I started to compare what I have different online and trailed it to the `techdocs.generator.runIn` setting. When I set it to `local` (as I have it online), then it works as on the video.

Here is a reproduction repository: https://github.com/PP-etc/backstage-vs-mermaid

**Comment by johanneswuerbach** [comment]
Glad that you found a solution :-)
